%YAML 1.2
# SPDX-FileCopyrightText: Copyright (c) 2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
extensions:
  - libgxf_std.so
  - libgxf_cuda.so
  - libgxf_multimedia.so
  - libgxf_serialization.so
  - libaja_source.so
  - libformat_converter.so
  - libholoviz.so
  - libsegmentation_postprocessor.so
  - libstream_playback.so
  - libtensor_rt.so

source: "replayer" # or "aja"

replayer:  # VideoStreamReplayer
  directory: "../data/ultrasound/video"
  basename: "ultrasound_256x256"
  frame_rate: 0 # as specified in timestamps
  repeat: true # default: false
  realtime: true # default: true
  count: 0 # default: 0 (no frame count restriction)

aja:  # AJASourceOp
  width: 1920
  height: 1080
  rdma: true
  enable_overlay: false

drop_alpha_channel:  # FormatConverter
  in_dtype: "rgba8888"
  in_tensor_name: source_video
  out_tensor_name: source_video
  out_dtype: "rgb888"

segmentation_preprocessor:  # FormatConverter
    # in_tensor_name: source_video
    out_tensor_name: source_video
    out_dtype: "float32"
    resize_width: 256
    resize_height: 256

segmentation_inference:  # TensorRtInference
  model_file_path: ../data/ultrasound/model/us_unet_256x256_nhwc.onnx
  engine_cache_dir: ../data/ultrasound/model/us_unet_256x256_nhwc_engines
  input_tensor_names:
    - source_video
  input_binding_names:
    - INPUT__0
  output_tensor_names:
    - inference_output_tensor
  output_binding_names:
    - OUTPUT__0
  force_engine_update: false
  verbose: true
  max_workspace_size: 2147483648
  enable_fp16_: false

segmentation_postprocessor:  # Postprocessor
  in_tensor_name: inference_output_tensor
  network_output_type: softmax
  data_format: nchw

segmentation_visualizer:  # Holoviz
  color_lut: [
    [0.65, 0.81, 0.89, 0.1],
    [0.2, 0.63, 0.17, 0.7],
    [0.98, 0.6, 0.6, 0.7],
    [0.89, 0.1, 0.11, 0.7],
    [0.99, 0.75, 0.44, 0.7],
    [1.0, 0.5, 0.0, 0.7],
    [0.0, 0.0, 0.0, 0.1]
    ]
